-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "priceCommunity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceRegular" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "price100g" SET DEFAULT 0,
ALTER COLUMN "price200g" SET DEFAULT 0;
